export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

// AUTENTICAÇÃO
export const AUTH_LOGIN	      = 'AUTH_LOGIN';
export const AUTH_LOGOUT      = 'AUTH_LOGOUT';
export const AUTH_CHECK_TOKEN = 'AUTH_CHECK_TOKEN';

// USER

export const SET_USER  = 'SET_USER';
export const SET_USERS = 'SET_USERS';
export const EDIT_USER = 'EDIT_USER';

// DICAS

export const SET_DICAS          = 'SET_DICAS';
export const DELETE_DICA        = 'DELETE_DICA';
export const PREPARE_EDIT_DICA  = 'PREPARE_EDIT_DICA';
export const PREPARE_VIEW_DICA  = 'PREPARE_VIEW_DICA';

// TRATAMENTOS

export const SET_TRATAMENTOS          = 'SET_TRATAMENTOS';
export const DELETE_TRATAMENTO        = 'DELETE_TRATAMENTO';
export const PREPARE_EDIT_TRATAMENTO  = 'PREPARE_EDIT_TRATAMENTO';
export const PREPARE_VIEW_TRATAMENTO  = 'PREPARE_VIEW_TRATAMENTO';

// CIRURGIAS

export const SET_CIRURGIAS          = 'SET_CIRURGIAS';
export const DELETE_CIRURGIA        = 'DELETE_CIRURGIA';
export const PREPARE_EDIT_CIRURGIA  = 'PREPARE_EDIT_CIRURGIA';
export const PREPARE_VIEW_CIRURGIA  = 'PREPARE_VIEW_CIRURGIA';

// HOSPITAIS

export const SET_HOSPITAIS          = 'SET_HOSPITAIS';
export const DELETE_HOSPITAL        = 'DELETE_HOSPITAL';
export const PREPARE_EDIT_HOSPITAL  = 'PREPARE_EDIT_HOSPITAL';

// DEPOIMENTOS

export const SET_DEPOIMENTOS         = 'SET_DEPOIMENTOS';
export const PREPARE_VIEW_DEPOIMENTO = 'PREPARE_VIEW_DEPOIMENTO';

// EVOLUÇÕES

export const SET_EVOLUCOES = 'SET_EVOLUCOES';